export const SECTION_PATTERNS: Record<string, string[]> = {
  summary: [
    'professional summary',
    'career objective',
    'objective',
    'profile',
    'about me',
    'overview',
    'introduction',
    'personal statement',
    'executive summary',
    'career summary',
    'professional profile',
    'bio',
    'about',
    'professional overview',
    'who i am',
    'statement',
    'summary of qualifications',
    'qualifications summary',
    'summary',
  ],
  experience: [
    'experience',
    'work experience',
    'professional experience',
    'employment history',
    'work history',
    'career history',
    'positions held',
    'professional background',
    'relevant experience',
    'employment',
    'career',
    'work',
    'job history',
    'work record',
    'professional history',
    'experience and achievements',
    'career experience',
    'internship experience',
    'ux projects',
    'relevant projects',
    'professional experience and projects',
  ],
  education: [
    'education',
    'academic background',
    'educational background',
    'qualifications',
    'academic qualifications',
    'degrees',
    'training and education',
    'academic history',
    'educational history',
    'schooling',
    'studies',
    'academic credentials',
    'education and training',
    'educational qualifications',
    'university',
    'college',
  ],
  skills: [
    'skills',
    'technical skills',
    'core skills',
    'key skills',
    'competencies',
    'expertise',
    'technologies',
    'tools and technologies',
    'technical proficiencies',
    'areas of expertise',
    'skill set',
    'capabilities',
    'technical expertise',
    'professional skills',
    'technical competencies',
    'skills and technologies',
    'tools and skills',
    'programming languages',
    'technologies and tools',
    'software and tools',
    'hard skills',
    'soft skills',
    'skills and competencies',
    'technical qualifications',
  ],
  certifications: [
    'certifications',
    'certificates',
    'licenses and certifications',
    'professional development',
    'credentials',
    'accreditations',
    'professional certifications',
    'courses and certifications',
    'training',
    'licenses',
    'qualifications',
    'professional qualifications',
    'awards and certifications',
    'courses completed',
    'certification',
  ],
  languages: [
    'languages',
    'language skills',
    'linguistic skills',
    'language proficiency',
    'spoken languages',
    'language abilities',
  ],
  projects: [
    'projects',
    'personal projects',
    'key projects',
    'notable projects',
    'selected projects',
    'portfolio',
    'side projects',
    'open source',
    'github projects',
    'personal work',
    'independent projects',
    'freelance projects',
    'technical projects',
    'project experience',
  ],
  awards: [
    'awards',
    'honors',
    'achievements',
    'awards and recognition',
    'accomplishments',
    'recognition',
    'accolades',
    'prizes',
    'honours',
    'awards and honours',
    'achievements and awards',
  ],
  volunteer: [
    'volunteer',
    'volunteering',
    'volunteer experience',
    'community involvement',
    'civic activities',
    'community service',
    'pro bono',
    'voluntary work',
    'voluntary experience',
  ],
  publications: [
    'publications',
    'papers',
    'research',
    'articles',
    'books',
    'writing',
    'published work',
    'research papers',
  ],
  interests: [
    'interests',
    'hobbies',
    'hobbies and interests',
    'personal interests',
    'activities',
    'outside interests',
    'extracurricular activities',
  ],
  references: [
    'references',
    'referees',
    'professional references',
    'references available',
  ],
  personal_information: [
    'personal information',
    'personal details',
    'personal data',
    'contact information',
    'contact details',
    'personal profile',
  ],
  links: [
    'links',
    'social links',
    'online presence',
    'social media',
    'profiles',
    'online profiles',
    'digital presence',
    'connect',
    'find me online',
    'web presence',
  ],
};

export const ALL_SECTION_HEADERS = Object.values(SECTION_PATTERNS).flat();

export const SKILL_DICTIONARY: Record<string, string> = {
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  python: 'Python',
  java: 'Java',
  c: 'C',
  'c++': 'C++',
  'c#': 'C#',
  csharp: 'C#',
  go: 'Go',
  rust: 'Rust',
  ruby: 'Ruby',
  php: 'PHP',
  swift: 'Swift',
  kotlin: 'Kotlin',
  scala: 'Scala',
  r: 'R',
  matlab: 'MATLAB',
  perl: 'Perl',
  haskell: 'Haskell',
  elixir: 'Elixir',
  clojure: 'Clojure',
  dart: 'Dart',
  lua: 'Lua',
  julia: 'Julia',
  'objective-c': 'Objective-C',
  assembly: 'Assembly',
  cobol: 'COBOL',
  fortran: 'Fortran',
  vba: 'VBA',
  'f#': 'F#',
  groovy: 'Groovy',

  react: 'React',
  vue: 'Vue',
  angular: 'Angular',
  svelte: 'Svelte',
  'next.js': 'Next.js',
  'nuxt.js': 'Nuxt.js',
  gatsby: 'Gatsby',
  remix: 'Remix',
  astro: 'Astro',
  html: 'HTML',
  html5: 'HTML5',
  css: 'CSS',
  css3: 'CSS3',
  sass: 'Sass',
  scss: 'SCSS',
  less: 'Less',
  'tailwind css': 'Tailwind CSS',
  bootstrap: 'Bootstrap',
  'material ui': 'Material UI',
  'chakra ui': 'Chakra UI',
  'shadcn/ui': 'shadcn/ui',
  'framer motion': 'Framer Motion',
  'three.js': 'Three.js',
  'd3.js': 'D3.js',
  'chart.js': 'Chart.js',
  jquery: 'jQuery',
  webpack: 'Webpack',
  vite: 'Vite',
  babel: 'Babel',
  eslint: 'ESLint',
  prettier: 'Prettier',

  'node.js': 'Node.js',
  nodejs: 'Node.js',
  express: 'Express',
  nestjs: 'NestJS',
  fastapi: 'FastAPI',
  django: 'Django',
  flask: 'Flask',
  'spring boot': 'Spring Boot',
  rails: 'Rails',
  laravel: 'Laravel',
  'asp.net': 'ASP.NET',
  gin: 'Gin',
  echo: 'Echo',
  fiber: 'Fiber',
  hapi: 'Hapi',
  koa: 'Koa',
  fastify: 'Fastify',
  graphql: 'GraphQL',
  rest: 'REST',
  'rest api': 'REST API',
  grpc: 'gRPC',
  websockets: 'WebSockets',
  trpc: 'tRPC',

  postgresql: 'PostgreSQL',
  mysql: 'MySQL',
  sqlite: 'SQLite',
  'sql server': 'SQL Server',
  oracle: 'Oracle',
  mongodb: 'MongoDB',
  dynamodb: 'DynamoDB',
  cassandra: 'Cassandra',
  redis: 'Redis',
  elasticsearch: 'Elasticsearch',
  firebase: 'Firebase',
  supabase: 'Supabase',
  planetscale: 'PlanetScale',
  cockroachdb: 'CockroachDB',
  influxdb: 'InfluxDB',
  neo4j: 'Neo4j',
  prisma: 'Prisma',
  sequelize: 'Sequelize',
  typeorm: 'TypeORM',
  mongoose: 'Mongoose',
  drizzle: 'Drizzle',

  aws: 'AWS',
  gcp: 'GCP',
  azure: 'Azure',
  vercel: 'Vercel',
  railway: 'Railway',
  render: 'Render',
  heroku: 'Heroku',
  netlify: 'Netlify',
  cloudflare: 'Cloudflare',
  digitalocean: 'DigitalOcean',
  docker: 'Docker',
  kubernetes: 'Kubernetes',
  terraform: 'Terraform',
  ansible: 'Ansible',
  jenkins: 'Jenkins',
  'github actions': 'GitHub Actions',
  circleci: 'CircleCI',
  'gitlab ci': 'GitLab CI',
  'travis ci': 'Travis CI',
  helm: 'Helm',
  prometheus: 'Prometheus',
  grafana: 'Grafana',
  datadog: 'Datadog',
  sentry: 'Sentry',
  'new relic': 'New Relic',
  nginx: 'Nginx',
  apache: 'Apache',

  git: 'Git',
  github: 'GitHub',
  gitlab: 'GitLab',
  bitbucket: 'Bitbucket',
  jira: 'Jira',
  confluence: 'Confluence',
  notion: 'Notion',
  slack: 'Slack',
  linear: 'Linear',
  figma: 'Figma',
  sketch: 'Sketch',
  'adobe xd': 'Adobe XD',
  zeplin: 'Zeplin',
  invision: 'InVision',
  miro: 'Miro',
  postman: 'Postman',
  insomnia: 'Insomnia',
  swagger: 'Swagger',
  'vs code': 'VS Code',
  intellij: 'IntelliJ',
  xcode: 'Xcode',
  'android studio': 'Android Studio',
  webflow: 'Webflow',

  jest: 'Jest',
  vitest: 'Vitest',
  mocha: 'Mocha',
  chai: 'Chai',
  cypress: 'Cypress',
  playwright: 'Playwright',
  selenium: 'Selenium',
  puppeteer: 'Puppeteer',
  'testing library': 'Testing Library',
  junit: 'JUnit',
  pytest: 'pytest',
  rspec: 'RSpec',
  supertest: 'Supertest',
  k6: 'k6',
  locust: 'Locust',

  tensorflow: 'TensorFlow',
  pytorch: 'PyTorch',
  'scikit-learn': 'scikit-learn',
  pandas: 'Pandas',
  numpy: 'NumPy',
  matplotlib: 'Matplotlib',
  seaborn: 'Seaborn',
  jupyter: 'Jupyter',
  keras: 'Keras',
  'hugging face': 'Hugging Face',
  opencv: 'OpenCV',
  spark: 'Spark',
  hadoop: 'Hadoop',
  airflow: 'Airflow',
  dbt: 'dbt',
  tableau: 'Tableau',
  'power bi': 'Power BI',
  looker: 'Looker',
  bigquery: 'BigQuery',
  snowflake: 'Snowflake',
  databricks: 'Databricks',

  'adobe photoshop': 'Adobe Photoshop',
  photoshop: 'Adobe Photoshop',
  'adobe illustrator': 'Adobe Illustrator',
  illustrator: 'Adobe Illustrator',
  'adobe premiere': 'Adobe Premiere',
  'adobe after effects': 'Adobe After Effects',
  canva: 'Canva',
  indesign: 'InDesign',
  principle: 'Principle',
  framer: 'Framer',
  protopie: 'ProtoPie',
  wireframing: 'Wireframing',
  prototyping: 'Prototyping',
  'design systems': 'Design Systems',
  'user research': 'User Research',
  'usability testing': 'Usability Testing',
  'a/b testing': 'A/B Testing',
  'information architecture': 'Information Architecture',
  'interaction design': 'Interaction Design',

  agile: 'Agile',
  scrum: 'Scrum',
  kanban: 'Kanban',
  safe: 'SAFe',
  waterfall: 'Waterfall',
  devops: 'DevOps',
  'ci/cd': 'CI/CD',
  'ci cd': 'CI/CD',
  tdd: 'TDD',
  bdd: 'BDD',
  ddd: 'DDD',
  microservices: 'Microservices',
  serverless: 'Serverless',
  'event-driven': 'Event-Driven',
  'event driven': 'Event-Driven',
  solidity: 'Solidity',
  truffle: 'Truffle',
  hardhat: 'Hardhat',
  wagmi: 'wagmi',
  ethers: 'Ethers.js',
  web3: 'Web3',
  metamask: 'MetaMask',
  ipfs: 'IPFS',
  chainlink: 'Chainlink',
  'smart contracts': 'Smart Contracts',
  defi: 'DeFi',
  nft: 'NFT',
  polygon: 'Polygon',
  binance: 'Binance',
  avalanche: 'Avalanche',
  arbitrum: 'Arbitrum',
  optimism: 'Optimism',
  foundry: 'Foundry',
  alchemy: 'Alchemy',
  infura: 'Infura',
  solid: 'SOLID',
  'clean architecture': 'Clean Architecture',
  'design patterns': 'Design Patterns',

  sql: 'SQL',
  nosql: 'NoSQL',
  linux: 'Linux',
  unix: 'Unix',
  bash: 'Bash',
  powershell: 'PowerShell',
  zsh: 'Zsh',
  restful: 'RESTful',
  api: 'API',
  oop: 'OOP',
  'machine learning': 'Machine Learning',
  'deep learning': 'Deep Learning',
  'natural language processing': 'NLP',
  nlp: 'NLP',
  llm: 'LLM',
  'large language models': 'LLMs',
  'data analysis': 'Data Analysis',
  'data visualization': 'Data Visualization',
  'data engineering': 'Data Engineering',
  'data science': 'Data Science',
  'data pipeline': 'Data Pipeline',
  etl: 'ETL',

  'product management': 'Product Management',
  'project management': 'Project Management',
  'stakeholder management': 'Stakeholder Management',
  'cross-functional collaboration': 'Cross-Functional Collaboration',
  leadership: 'Leadership',
  mentoring: 'Mentoring',
  'team management': 'Team Management',
  'technical writing': 'Technical Writing',
  'public speaking': 'Public Speaking',
  presentation: 'Presentation',
  negotiation: 'Negotiation',
  'conflict resolution': 'Conflict Resolution',
  'critical thinking': 'Critical Thinking',
  'problem solving': 'Problem Solving',
  'analytical skills': 'Analytical Skills',
  communication: 'Communication',
  collaboration: 'Collaboration',
  'time management': 'Time Management',
  adaptability: 'Adaptability',
  creativity: 'Creativity',
  'attention to detail': 'Attention to Detail',
  organization: 'Organization',
  'fast learner': 'Fast Learner',
  'self-motivated': 'Self-Motivated',
  'results-oriented': 'Results-Oriented',
  'detail-oriented': 'Detail-Oriented',
};

export const LANGUAGE_DICTIONARY: Record<string, string> = {
  english: 'English',
  spanish: 'Spanish',
  french: 'French',
  german: 'German',
  mandarin: 'Mandarin',
  chinese: 'Chinese',
  japanese: 'Japanese',
  korean: 'Korean',
  arabic: 'Arabic',
  portuguese: 'Portuguese',
  italian: 'Italian',
  russian: 'Russian',
  dutch: 'Dutch',
  swedish: 'Swedish',
  norwegian: 'Norwegian',
  danish: 'Danish',
  finnish: 'Finnish',
  polish: 'Polish',
  turkish: 'Turkish',
  hindi: 'Hindi',
  bengali: 'Bengali',
  urdu: 'Urdu',
  swahili: 'Swahili',
  hebrew: 'Hebrew',
  greek: 'Greek',
  thai: 'Thai',
  vietnamese: 'Vietnamese',
  indonesian: 'Indonesian',
  malay: 'Malay',
  tagalog: 'Tagalog',
  punjabi: 'Punjabi',
  tamil: 'Tamil',
  telugu: 'Telugu',
  marathi: 'Marathi',
  gujarati: 'Gujarati',
  romanian: 'Romanian',
  hungarian: 'Hungarian',
  czech: 'Czech',
  slovak: 'Slovak',
  bulgarian: 'Bulgarian',
  croatian: 'Croatian',
  serbian: 'Serbian',
  ukrainian: 'Ukrainian',
  catalan: 'Catalan',
  welsh: 'Welsh',
  irish: 'Irish',
  afrikaans: 'Afrikaans',
  persian: 'Persian',
  farsi: 'Farsi',
  pashto: 'Pashto',
  sindhi: 'Sindhi',
  nepali: 'Nepali',
  sinhala: 'Sinhala',
  khmer: 'Khmer',
  burmese: 'Burmese',
  lao: 'Lao',
  mongolian: 'Mongolian',
  tibetan: 'Tibetan',
  amharic: 'Amharic',
  somali: 'Somali',
  hausa: 'Hausa',
  yoruba: 'Yoruba',
  igbo: 'Igbo',
  zulu: 'Zulu',
  xhosa: 'Xhosa',
  georgian: 'Georgian',
  armenian: 'Armenian',
  azerbaijani: 'Azerbaijani',
  estonian: 'Estonian',
  latvian: 'Latvian',
  lithuanian: 'Lithuanian',
  macedonian: 'Macedonian',
  albanian: 'Albanian',
  bosnian: 'Bosnian',
  slovenian: 'Slovenian',
  maltese: 'Maltese',
  icelandic: 'Icelandic',
  flemish: 'Flemish',
};

export const PROFICIENCY_MAP: Record<string, string> = {
  native: 'native',
  'mother tongue': 'native',
  'first language': 'native',
  'native speaker': 'native',
  c2: 'native',
  bilingual: 'native',
  fluent: 'fluent',
  'business fluent': 'fluent',
  'professional working proficiency': 'fluent',
  'full professional proficiency': 'fluent',
  c1: 'fluent',
  'near-native': 'fluent',
  advanced: 'advanced',
  'upper intermediate': 'advanced',
  b2: 'advanced',
  professional: 'advanced',
  intermediate: 'intermediate',
  conversational: 'intermediate',
  b1: 'intermediate',
  'working knowledge': 'intermediate',
  basic: 'basic',
  elementary: 'basic',
  beginner: 'basic',
  a1: 'basic',
  a2: 'basic',
  limited: 'basic',
  foundational: 'basic',
};
