import type { LocalData } from '../../../pages/editor/types'

export const SPARSE_RESUME: LocalData = {
  title: 'Sparse Resume',
  name: 'Jane Doe',
  summary: 'Experienced professional with 5+ years in project management.',
  contact: {
    email: 'jane@example.com',
    phone: '(555) 123-4567',
    location: 'San Francisco, CA',
    linkedin: 'linkedin.com/in/janedoe',
    website: 'janedoe.com',
    github: 'github.com/janedoe',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  experience: [
    {
      company: 'TechCorp',
      title: 'Senior Project Manager',
      startDate: '2021-03',
      endDate: '',
      current: true,
      bullets: [
        'Led cross-functional teams of 15+ members',
        'Delivered $2M projects on time and under budget',
      ],
    },
  ],
  education: [
    {
      institution: 'Stanford University',
      degree: 'MBA',
      field: 'Business Administration',
      startDate: '2018-09',
      endDate: '2020-06',
      gpa: '3.8',
    },
  ],
  skills: [
    { name: 'Project Management', category: 'Management' },
    { name: 'Agile', category: 'Methodology' },
    { name: 'Leadership', category: 'Soft Skills' },
  ],
  certifications: [],
  languages: ['English', 'Spanish'],
  links: [
    { title: 'LinkedIn', url: 'linkedin.com/in/janedoe' },
    { title: 'Website', url: 'janedoe.com' },
  ],
  customSections: [],
  sectionOrder: ['summary', 'experience', 'education', 'skills', 'certifications', 'languages', 'links'],
  design: {
    headingFont: 'DM Serif Display',
    bodyFont: 'Plus Jakarta Sans',
    bodyFontSize: 10,
    lineSpacing: 1.5,
    primaryColor: '#0F6E56',
    secondaryColor: '#475569',
    columnLayout: 'single-column',
    margins: 3,
    sectionSpacing: 3,
  },
  editMode: 'guided',
}

export const DENSE_RESUME: LocalData = {
  title: 'Dense Resume',
  name: 'John Smith',
  summary: 'Full-stack software engineer with 10+ years of experience building scalable web applications. Passionate about clean code, test-driven development, and mentoring junior developers. Expert in React, Node.js, Python, and cloud infrastructure. Proven track record of leading teams and delivering high-impact projects.',
  contact: {
    email: 'john@example.com',
    phone: '(555) 987-6543',
    location: 'New York, NY',
    linkedin: 'linkedin.com/in/johnsmith',
    website: 'johnsmith.dev',
    github: 'github.com/johnsmith',
  },
  experience: [
    {
      company: 'MegaTech Inc.',
      title: 'Lead Software Engineer',
      startDate: '2020-01',
      endDate: '',
      current: true,
      bullets: [
        'Architected microservices platform serving 10M+ daily active users',
        'Led team of 8 engineers, mentored 3 junior developers to mid-level',
        'Reduced API response times by 60% through Redis caching and query optimization',
        'Implemented CI/CD pipeline reducing deployment time from 2 hours to 15 minutes',
        'Built real-time analytics dashboard using React, D3.js, and WebSocket',
      ],
    },
    {
      company: 'StartupXYZ',
      title: 'Senior Software Engineer',
      startDate: '2017-06',
      endDate: '2019-12',
      current: false,
      bullets: [
        'Built MVP from scratch using React, Node.js, and PostgreSQL',
        'Designed and implemented RESTful API serving 500K+ requests/day',
        'Integrated payment processing with Stripe, handling $1M+ in transactions',
        'Implemented automated testing suite achieving 95% code coverage',
      ],
    },
    {
      company: 'BigCorp',
      title: 'Software Engineer',
      startDate: '2014-03',
      endDate: '2017-05',
      current: false,
      bullets: [
        'Developed customer-facing web application using Angular and .NET',
        'Optimized database queries reducing load times by 40%',
        'Participated in agile ceremonies and contributed to sprint planning',
      ],
    },
  ],
  education: [
    {
      institution: 'MIT',
      degree: 'BS',
      field: 'Computer Science',
      startDate: '2010-09',
      endDate: '2014-05',
      gpa: '3.9',
    },
  ],
  skills: [
    { name: 'React', category: 'Frontend' },
    { name: 'TypeScript', category: 'Languages' },
    { name: 'Node.js', category: 'Backend' },
    { name: 'Python', category: 'Languages' },
    { name: 'PostgreSQL', category: 'Database' },
    { name: 'AWS', category: 'Cloud' },
    { name: 'Docker', category: 'DevOps' },
    { name: 'Kubernetes', category: 'DevOps' },
    { name: 'GraphQL', category: 'API' },
    { name: 'Redis', category: 'Database' },
    { name: 'MongoDB', category: 'Database' },
    { name: 'Git', category: 'Tools' },
    { name: 'CI/CD', category: 'DevOps' },
    { name: 'Agile', category: 'Methodology' },
    { name: 'Technical Leadership', category: 'Soft Skills' },
  ],
  certifications: [
    { name: 'AWS Solutions Architect Professional', issuer: 'Amazon Web Services', date: '2022-03' },
    { name: 'Kubernetes Administrator (CKA)', issuer: 'CNCF', date: '2021-09' },
    { name: 'Google Cloud Professional Cloud Architect', issuer: 'Google', date: '2023-01' },
  ],
  languages: ['English', 'Spanish', 'Japanese'],
  links: [
    { title: 'LinkedIn', url: 'linkedin.com/in/johnsmith' },
    { title: 'GitHub', url: 'github.com/johnsmith' },
    { title: 'Website', url: 'johnsmith.dev' },
    { title: 'Blog', url: 'johnsmith.dev/blog' },
  ],
  customSections: [],
  sectionOrder: ['summary', 'experience', 'education', 'skills', 'certifications', 'languages', 'links'],
  design: {
    headingFont: 'DM Serif Display',
    bodyFont: 'Plus Jakarta Sans',
    bodyFontSize: 10,
    lineSpacing: 1.5,
    primaryColor: '#1E3A5F',
    secondaryColor: '#475569',
    columnLayout: 'single-column',
    margins: 3,
    sectionSpacing: 3,
  },
  editMode: 'guided',
}

export const PHOTO_RESUME: LocalData = {
  ...SPARSE_RESUME,
  title: 'Photo Resume',
  name: 'Sarah Chen',
  contact: {
    ...SPARSE_RESUME.contact,
    photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
  },
}
